### ISSUE TITLE
提几个小建议

### ISSUE THREAD

**Issue by liaohui5** [amojs-xy/delfin#3]
1. 项目没有 README.md
2. 没有.gitignore文件, 忽略 .vscode 没用的文件
3. 文档可以用 github pages 免费生成一个在线的静态网页

虽然代码是最重要的, 但是相关工具的利用可以让项目更加分 😄

**Comment by libondev** [comment]
在写了在写了【滑稽】

**Comment by amojs-xy** [comment]
在写了在写了【滑稽】

**Comment by amojs-xy** [comment]
在写了在写了【滑稽】
